---
abstract: 'use the dogeapi.com API from Perl'
author:
  - 'chromatic <chromatic@wgz.org>'
build_requires:
  File::Find: 0
  Test::Mock::LWP: 0
  Test::More: 0
  Test::Most: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-Dogecoin
requires:
  Carp: 0
  HTTP::Headers: 0
  JSON: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Moo: 0
  URI::QueryParam: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/chromatic/Finance-Dogecoin
  repository: https://github.com/chromatic/Finance-Dogecoin.git
version: 1.20140129.2055
